version: '2'

services:
   playfun-node00:
      container_name: playfun-node00
      # image: corysanin/playfun:latest
      build:
         context: ./
         dockerfile: ./Dockerfile
      command:
         - "--helper"
      volumes:
         - ./config:/playfun/config

   playfun-node01:
      container_name: playfun-node01
      build:
         context: ./
         dockerfile: ./Dockerfile
      command:
         - "--helper"
      volumes:
         - ./config:/playfun/config

   playfun-node02:
      container_name: playfun-node02
      build:
         context: ./
         dockerfile: ./Dockerfile
      command:
         - "--helper"
      volumes:
         - ./config:/playfun/config

   playfun-node03:
      container_name: playfun-node03
      build:
         context: ./
         dockerfile: ./Dockerfile
      command:
         - "--helper"
      volumes:
         - ./config:/playfun/config

   playfun-master:
      container_name: playfun-master
      build:
         context: ./
         dockerfile: ./Dockerfile
      command:
         - "--master"
         - "playfun-node00"
         - "playfun-node01"
         - "playfun-node02"
         - "playfun-node03"
      volumes:
         - ./config:/playfun/config

